[package]
name = "ark-ec"
version = "0.1.0"
authors = [ "arkworks contributors" ]
description = "A library for elliptic curves and pairings"
homepage = "https://arkworks.rs"
repository = "https://github.com/arkworks-rs/algebra"
documentation = "https://docs.rs/ark-ec/"
keywords = ["cryptography", "finite fields", "elliptic curves" ]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
ark-std = { git = "https://github.com/arkworks-rs/utils", default-features = false }
ark-serialize = { path = "../serialize", default-features = false }
ark-ff = { path = "../ff", default-features = false }
derivative = { version = "2", features = ["use_core"] }
num-traits = { version = "0.2", default-features = false }
rayon = { version = "1", optional = true }
itertools = { version = "0.9.0", default-features = false }
either = { version = "1.6.0", default-features = false }
thread-id = { version = "3.3.0", optional = true }
backtrace = { version = "0.3", optional = true }
accel = { git = "https://github.com/jon-chuang/accel", package = "accel", optional = true }
peekmore = "0.5.6"
closure = { version = "0.3.0", optional = true }
lazy_static = { version = "1.4.0", optional = true }
serde_json = { version = "1.0.58", optional = true }
dirs = { version = "1.0.5", optional = true }
log = { version = "0.4.11", optional = true }
paste = "0.1"
zeroize = { version = "1", default-features = false, features = ["zeroize_derive"] }

[dev-dependencies]
rand_xorshift = "0.2"

[features]
cuda = [ "std", "parallel", "accel", "lazy_static", "serde_json", "dirs", "closure", "log" ]
default = []
std = [ "ark-std/std", "ark-ff/std", "ark-serialize/std" ]
parallel = [ "std", "rayon", "ark-std/parallel" ]
