[package]
name = "glv_lattice_basis"
version = "0.1.0"
authors = ["Jonathan Chuang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bls12-381 = { git = "https://github.com/arkworks-rs/curves", features = ["curve"], default-features = false }
ark-ff = { path = "../../ff", default-features = false }
ark-ec = { path = "../../ec", default-features = false }
num-traits = { version = "0.2", default-features = false }
num-bigint = "0.4.0"

[features]
default = [ "std" ]
std = []
